# Generated by Django 5.2.4 on 2025-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='email',
        ),
        migrations.RemoveField(
            model_name='app',
            name='name',
        ),
    ]
