# Generated by Django 5.2.4 on 2025-07-22 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_app_email_remove_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='email',
            field=models.CharField(default='python', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
